# Generated by Django 5.2.12 on 2026-04-22 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0075_rename_accounts_aeo_prompt_agg_profile_run_status_idx_acct_aeoagg_runstat_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionsGeneratedPageSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_key', models.CharField(db_index=True, help_text='Actions UI card id (e.g. seo-step-0, aeo strategy stable id).', max_length=512)),
                ('content_hash', models.CharField(blank=True, db_index=True, default='', help_text='SHA-256 hex of canonical generation inputs; cache hit only when this matches the request.', max_length=64)),
                ('page_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Actions generated page snapshot',
                'verbose_name_plural': 'Actions generated page snapshots',
            },
        ),
        migrations.RenameIndex(
            model_name='thirdpartyapirequestlog',
            new_name='accounts_th_provide_a62585_idx',
            old_name='acc_tpapi_prov_crt_idx',
        ),
        migrations.RenameIndex(
            model_name='thirdpartyapirequestlog',
            new_name='accounts_th_busines_607009_idx',
            old_name='acc_tpapi_prof_crt_idx',
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='aeo_full_phase_eta_state',
            field=models.JSONField(blank=True, default=dict, help_text='Rolling completion durations + recorded prompt hashes for AI Visibility ETA.'),
        ),
        migrations.AlterField(
            model_name='onboardingonpagecrawl',
            name='topic_clusters',
            field=models.JSONField(blank=True, default=dict, help_text='Topic clusters: crawl seeds matched to ranked keywords (clusters, unclustered, stats).'),
        ),
        migrations.AlterField(
            model_name='thirdpartyapirequestlog',
            name='provider',
            field=models.CharField(choices=[('dataforseo', 'DataForSEO'), ('openai', 'OpenAI'), ('gemini', 'Google Gemini'), ('perplexity', 'Perplexity')], db_index=True, max_length=32),
        ),
        migrations.AddIndex(
            model_name='businessprofilemembership',
            index=models.Index(fields=['user'], name='accounts_bu_user_id_f59ddd_idx'),
        ),
        migrations.AddIndex(
            model_name='businessprofilemembership',
            index=models.Index(fields=['business_profile'], name='accounts_bu_busines_0bfe10_idx'),
        ),
        migrations.AddField(
            model_name='actionsgeneratedpagesnapshot',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_page_snapshots', to='accounts.businessprofile'),
        ),
        migrations.AddConstraint(
            model_name='actionsgeneratedpagesnapshot',
            constraint=models.UniqueConstraint(fields=('profile', 'action_key'), name='uniq_actions_genpage_profile_action'),
        ),
    ]
